config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :poems
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'poems#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
#!/usr/bin/env ruby
require 'csv'

class Author < ApplicationRecord
	def self.import_from_file
		Author.delete_all
		artists = CSV.read("artists.csv", { :col_sep => "\t", :headers => true})
		artists.each do |artist|
			# puts artist.inspect
			Author.create!(artist.to_hash)
		end
	end
end

app/models/poem.rb
class Poem < ApplicationRecord
	has_one :author
	def author
		return Author.find_by(:id => self.author_id)
	end

	def hanji_with_hongim
		punctuations = ["。","「","」","，","？","．"]
		tone_marks = [" ","ˋ","˪","ㆴ˙","ㆵ˙","ㆶ˙","ㆷ˙","ㆴ","ㆵ","ㆶ","ㆷ","ˊ","˫"]
		special_tone_marks = ["ㆴ","ㆵ","ㆶ","ㆷ"]

		result = []
		hanji_array = self.hanji.split("\n")
		hongim_array = self.hongim.split("\n")
		for index in (0...hanji_array.length)
			hanjis = hanji_array[index]
			hongims = hongim_array[index]
			sentence = ""
			for j in (0...hanjis.length)
				if punctuations.include?(hongims[0])
					sentence += "<ruby>" + hanjis[j] + "</ruby>"
					hongims.slice! hongims[0]
				else
					hongim_combo = ""

					if hongims == nil or hongims.length == 0
						sentence += "<ruby>" + hanjis[j] + "</ruby>"
					else
						while hongims != nil and !tone_marks.include?(hongims[0])
							if hongims == nil or hongims[0] == nil
								break
							else
								hongim_combo += hongims[0]
								hongims.slice! hongims[0]
							end
						end

						if hongims != nil
							if hongims.length > 1
								candidate_tone = hongims[0]
								if special_tone_marks.include?(candidate_tone)
									# When end with p, t, k, which might include dot after it
									candidate_tone_2 = hongims[0] + hongims[1]
									if tone_marks.include?(candidate_tone_2)
										# Is p, t, k with dot
										hongim_combo += candidate_tone_2
										hongims.slice! hongims[0]
										hongims.slice! hongims[0]
									else
										# Is p, t, k without dot
										hongim_combo += hongims[0]
										hongims.slice! hongims[0]
									end
								else
									if tone_marks.include?(hongims[0])
										hongim_combo += hongims[0]
										hongims.slice! hongims[0]
									end
								end
							elsif hongims.length > 0
								if tone_marks.include?(hongims[0])
									hongim_combo += hongims[0]
									hongims.slice! hongims[0]
								end
							end
						end
						sentence += "<ruby>" + hanjis[j] + "<rt>" + hongim_combo + "</rt></ruby>"
					end
				end
			end
			result << sentence
			result << "\n"
		end
		return result
	end

	def hanji_with_stailo
		result = []
		hanji_array = self.hanji.split("\n")
		stailo_array = self.stailo.split("\n")
		for index in (0...hanji_array.length)
			result << stailo_array[index]
			result << hanji_array[index]
			result << "\n"
		end
		return result
	end

	def self.import_from_file
		is_header = true
		author = ""
		title = ""
		author_hongim = ""
		title_hongim = ""
		author_tailo = ""
		title_tailo = ""
		hanji = ""
		hongim = ""
		tailo = ""

		File.open("hanji.txt", "r").each_line do |line|
  			if is_header
  				author_and_title = line.split("．")
  				author = author_and_title[0].squish!
  				title = author_and_title[1].squish!
  				is_header = false
  			else
  				hanji += line
  			end
		end

		is_header = true
		File.open("hongim.txt", "r").each_line do |line|
  			if is_header
  				author_and_title = line.split("．")
  				author_hongim = author_and_title[0].squish!
  				title_hongim = author_and_title[1].squish!
  				is_header = false
  			else
  				hongim += line
  			end
		end

		is_header = true
		File.open("tailo.txt", "r").each_line do |line|
  			if is_header
  				author_and_title = line.split(" · ")
  				author_tailo = author_and_title[0].squish!
  				title_tailo = author_and_title[1].squish!
  				is_header = false
  			else
  				tailo += line
  			end
		end

		puts "author = " + author
		puts "title = " + title
		puts "title_hongim = " + title_hongim
		puts "title_tailo = " + title_tailo
		puts "hanji = " + hanji
		puts "hongim = " + hongim
		puts "tailo = " + tailo

		author = Author.where(name: author).take!

		puts author.inspect
		Poem.where(:title => title, :author_id => author.id).destroy_all
		Poem.create!(:author_id => author.id, :title => title, :title_hongim => title_hongim, :title_tailo => title_tailo, :hanji => hanji, :hongim => hongim, :stailo => tailo)
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :stailo)
    end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy]

  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.all
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    @poem = Poem.new(poem_params)

    respond_to do |format|
      if @poem.save
        format.html { redirect_to @poem, notice: 'Poem was successfully created.' }
        format.json { render :show, status: :created, location: @poem }
      else
        format.html { render :new }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { render :show, status: :ok, location: @poem }
      else
        format.html { render :edit }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url, notice: 'Poem was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:hanji, :stailo, :hongim)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/authors/_form.html.slim
= form_for @author do |f|
  - if @author.errors.any?
    #error_explanation
      h2 = "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
      ul
        - @author.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :stailo
    = f.text_field :stailo
  .actions = f.submit

app/views/authors/edit.html.slim
h1 Editing author

== render 'form'

=> link_to 'Show', @author
'|
=< link_to 'Back', authors_path

app/views/authors/index.html.slim
nav aria-label="breadcrumb" style="border-radius: 0;"
  ol.breadcrumb
    li.breadcrumb-item
      a href="/"  主頁
    li.breadcrumb-item.active aria-current="page" 詩人

.text-center.title
  h6 ㄒㄧ ㆢㄧㄣˊ
  h1 詩人
- @authors.each_slice(3) do |authors|
  .row.artist-row
    - authors.each do |author|
      .col-md-4.text-center.artist-cell
        = link_to author
          h6
            = author.hongim
          h1
            = author.name

app/views/authors/new.html.slim
h1 New author

== render 'form'

= link_to 'Back', authors_path

app/views/authors/show.html.slim
nav aria-label="breadcrumb" style="border-radius: 0;"
	ol.breadcrumb
		li.breadcrumb-item
			a href="/"  主頁
		li.breadcrumb-item
			a href="/authors/"  詩人
		li.breadcrumb-item.active aria-current="page"
			= @author.name
.text-center#artist-header
	h6
		= @author.hongim
	h1
		= @author.name

app/views/layouts/application.html.slim
doctype html
html
	head
		title 唐詩三百首
		= csrf_meta_tags
    	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    	= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    	link crossorigin="anonymous" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" rel="stylesheet" /
		script crossorigin="anonymous" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" src="https://code.jquery.com/jquery-3.2.1.slim.min.js" 
		script crossorigin="anonymous" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" 
		script crossorigin="anonymous" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"
    body
    	= yield

app/views/poems/_form.html.slim
= form_for @poem do |f|
  - if @poem.errors.any?
    #error_explanation
      h2 = "#{pluralize(@poem.errors.count, "error")} prohibited this poem from being saved:"
      ul
        - @poem.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :hanji
    = f.text_field :hanji
  .field
    = f.label :stailo
    = f.text_field :stailo
  .field
    = f.label :hongim
    = f.text_field :hongim
  .actions = f.submit

app/views/poems/edit.html.slim
h1 Editing poem

== render 'form'

=> link_to 'Show', @poem
'|
=< link_to 'Back', poems_path

app/views/poems/index.html.slim
.text-right
	.btn-group.btn-group-phonetic.px-2.py-2 aria-label=("Phonetic Script") role="group" 
		button.btn.btn-phonetic type="button"  tai5-lo5
		button.btn.btn-phonetic type="button"  ㄏㆲ ㄧㆬ 


.text-center
  h1#main-title 唐詩三百首
  a.h2 href="/authors/" 訪詩人

br

- @poems.each do |poem|
  .row
    .col-md-4
    .col-md-4.text-center
      h2 = link_to "#{poem.author.name} #{poem.title}", poem
    .col-md-4

app/views/poems/new.html.slim
h1 New poem

== render 'form'

= link_to 'Back', poems_path

app/views/poems/show.html.slim
nav aria-label="breadcrumb" style="border-radius: 0;"
	ol.breadcrumb
		li.breadcrumb-item
			a href="/"  主頁
		li.breadcrumb-item
			a href="/authors/"  詩人
		li.breadcrumb-item
			a href="/authors/#{@poem.author.id}"
				= @poem.author.name
		li.breadcrumb-item.active aria-current="page"
			= @poem.title

.text-center style="margin-top:20vh;"
	
	h1
		ruby
			= @poem.author.name
			rt = @poem.author.hongim
		|．「
		ruby
			= @poem.title
			rt = @poem.title_hongim
		|」
	br
	article
		- @poem.hanji_with_hongim.each do |line|
			h2
				= raw line